services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432 -t 5 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: library_proj-backend:latest
    build: .
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db                    # имя сервиса БД в Docker Compose
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}                    # из .env
      - DB_USER=${DB_USER}                     # из .env
      - DB_PASSWORD=${DB_PASSWORD}  # из .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/library_proj

volumes:
  postgres_data: