# Generated by Django 6.0.1 on 2026-02-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "article",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=50, verbose_name="Жанр"),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год издания"
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество страниц"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступна для выдачи"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_authors",
                        to="authors.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="BookIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата выдачи"),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "is_returned",
                    models.BooleanField(
                        default=False, verbose_name="Возвращена ли книга?"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок возврата"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_issues",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выдача книги",
                "verbose_name_plural": "Выдачи книг",
                "ordering": ["user"],
            },
        ),
    ]
